import * as React from 'react';
import SiteContext from '../models/SiteContext';

const Terms = () => {   

    const context = React.useContext(SiteContext);

    return (
        <div id='menu' className='primary-color pb2'>
            <div className='inner-container mb2'>
                <h2 className='border-dotted bottom'>Terms</h2>
                <div className="body">
                    <h3>General</h3>
                    Welcome to the website (the "Website") of {context.settings.title}. Please carefully review these General Terms & Conditions, the {context.settings.title} Terms & Conditions, and the {context.settings.title} Privacy Policy (collectively, the "Terms & Conditions"), all of which collectively govern your use of and access to all of the Website and any and all content, data and information contained therein and your purchase of any products from this Website. YOUR USE OF ANY PORTION OF THIS WEBSITE, YOUR PURCHASE OF ANY PRODUCTS FROM THIS WEBSITE, AND/OR, WHERE APPLICABLE, YOUR AFFIRMATIVE CONSENT WHEN PROMPTED, CONSTITUTES YOUR UNCONDITIONAL ACCEPTANCE OF THE TERMS & CONDITIONS AND YOUR WILLINGNESS TO BE BOUND BY THESE TERMS & CONDITIONS, AS AMENDED OR SUPPLEMENTED FROM TIME TO TIME BY {context.settings.title}, IN ACCORDANCE WITH THESE TERMS & CONDITIONS. UNLESS YOU AGREE TO ALL OF THE TERMS & CONDITIONS CONTAINED HEREIN, YOU ARE STRICTLY PROHIBITED FROM USING OR ACCESSING THIS WEBSITE OR MAKING A PURCHASE.

                    <h3>Solely Intended for United States Users</h3>
                    Unless otherwise explicitly specified on the Website, the information on all of the Website is solely for use and access by persons residing in the United States, its territories, and possessions. {context.settings.title} controls and operates its Website from offices located in the United States and makes no representations or warranties that the information, products, or services contained on the Website is appropriate for use or access in other locations. Anyone using or accessing any of the Website from other locations does so on their own initiative and are responsible for compliance with local United States laws, if and to the extent applicable. {context.settings.title}'s makes no representation that the materials in the Website or the products described thereby are appropriate or available for use in other locations. If you access the Website from outside the United States, be advised the Website may contain references to products and services that are not available or are prohibited in your country.

                    <h3>Modifications of This Terms & Conditions</h3>
                    {context.settings.title} reserves the right to change, modify, amend, and/or update these Terms & Conditions at any time with or without prior notice. Your use of this Website following any such changes, modifications, amendments, and/or updates, and/or, where applicable, your affirmative consent when prompted, constitutes your unconditional agreement to follow and be bound by these Terms & Conditions as so changed, modified, amended, and/or updated. You are responsible for reviewing these Terms & Conditions each time you use or access any portion of this Website, and at any time you are prompted to do so.

                    <h3>Messaging</h3>
                    By agreeing to terms and submitting a form, you are consenting to receive text updates for subscriptions and order status from Twilio autodialer.
                    Consent is not a condition of purchase. Message and data rates may apply. Unsubscribe any time by clicking links provided in text messages.

                    <h3>Links</h3>
                    {context.settings.title} is not affiliated or associated with the sponsors, owners, or producers of any third-party websites linked to or from this Website. These linked sites are not under our control and {context.settings.title} explicitly disclaims any responsibility for the accuracy, content, or availability of the information, products, and/or services found on or through such third-party sites. {context.settings.title}'s urges you to review the terms and conditions and privacy policy posted on any site you visit before using the site or providing any personal data about yourself. {context.settings.title}'s does not endorse and has not taken any steps to confirm the accuracy or reliability of any of the information, products, or services contained on or through such third party sites. {context.settings.title}'s does not make any representations or warranties as to the security of any information (such as credit card and other sensitive information) you might give on any third-party site.

                    <h3>Use and Proprietary Rights</h3>
                    The Website and its contents are intended solely for personal, non-commercial use. Unless otherwise explicitly specified, all materials that are included in or are otherwise contained on this Website constitute the copyrights, patents, trademarks, trade dress, and/or other intellectual property owned, controlled, or licensed by {context.settings.title} or by third parties who have licensed their materials to {context.settings.title} and are protected by U.S. and international intellectual property laws. The compilation (i.e., the collection, arrangement, and assembly) of all materials on this Website is the exclusive property of {context.settings.title} or its licensors and is protected by U.S. and international copyright laws. Except as solely provided in the next sentence, no material from any portion of this Website may be copied, reproduced, republished, uploaded, posted, transmitted, or distributed in any way, shape, or form. All rights not expressly granted herein are reserved by {context.settings.title}. You may download one copy of the materials on any single computer for your personal, non-commercial use only, provided that: (a) you keep intact all copyright and other proprietary notices; (b) you do not use the materials in a manner that suggests an association with any of our products, services, or brands; and (c) you make no modifications to the materials.
                    <br /><br />
                    {context.settings.title} reserves the right at any time to: modify, suspend, or discontinue the Website or any service, content, feature, or product offered through the Website, with or without notice. You agree that {context.settings.title} shall not be liable to you or any third party for any modification, suspension, or discontinuance of the Website, or any service, content, feature, or products offered through the Website.
                    <br /><br />
                    In addition, you agree not to: (a) use or access this Website for any purpose that is unlawful or prohibited by these Terms & Conditions; (b) use or access this Website in a manner that could damage, disable, overburden, or impair any {context.settings.title} server or the networks connected to any {context.settings.title} server; (c) interfere with the proper operation of the Website or any third party's use and enjoyment of this Website; (d) attempt to gain unauthorized access to accounts, computer systems, or networks connected to any {context.settings.title} server through hacking, password mining, or by any other means, or use or launch any automated system, including without limitation, "robots," "spiders," or "offline readers," that accesses the Website in a manner that sends more request messages to the Website servers in a given period of time than a human can reasonably produce in the same period by using a conventional on-line web browser; or (e) to upload, post, or transmit any material that infringes on the rights of any third party or contains defamatory, libelous, abusive, obscene, or otherwise objectionable material (as determined by us in {context.settings.title} sole discretion).
                    <br /><br />
                    The Website is not intended for use by anyone under the age of 13. YOU MUST BE AT LEAST 13 YEARS OF AGE TO ACCESS AND USE THE WEBSITE. By accessing, using, and/or submitting information to or through the Website, you represent that you are at least 13 years of age. Anyone between age thirteen (13) and eighteen (18) may only use the Website under the supervision of his/her parent or a legal guardian. IF YOU ARE A PARENT/LEGAL GUARDIAN AND YOU PROVIDE YOUR CONSENT TO YOUR TEENAGER'S ACCESS TO AND USE OF THE WEBSITE, YOU AGREE TO BE BOUND BY THESE TERMS & CONDITIONS.
                    <br /><br />
                    The products sold on the Website are offered exclusively to individuals 18 years of age and older, who possess a valid credit card issued in their name. If you are under 18 years of age, you may use the Website only with involvement and oversight of a parent or guardian. {context.settings.title} reserves the right to refuse service or cancel orders in its sole discretion.
                    <br /><br />
                    You acknowledge and agree that {context.settings.title} may decline to provide access to the Website or stop (permanently or temporarily) providing the Website or the products offered on the Website (or any feature, program, or content within the Website) to you or other users at {context.settings.title} sole discretion, without notice or liability to you. You acknowledge and agree that if {context.settings.title} disables access to your account, you may be prevented from accessing the Website, your account details, or any files or other content that is contained in your account.

                    <h3>User Ids/Passwords</h3>
                    Use of certain features on the Website might be limited and/or require registration. {context.settings.title} will review and determine, in {context.settings.title} sole discretion, whether to accept your registration. {context.settings.title} shall have the right, in its sole discretion, to refuse or restrict anyone from accessing the Website(s) at any time, for any reason. Upon acceptance of your registration by {context.settings.title}, you may select your user ID and password (collectively "Password") for accessing and using the applicable portion of the Website. When registering for your Password, you must provide accurate and complete information.
                    <br /><br />
                    {context.settings.title} reserves the right to require you to periodically change your Password. You agree to use your best efforts to maintain the security of your Password. You shall not disclose your Password to anyone else, and you shall not use anyone else's Password. You agree to notify {context.settings.title} immediately about any unauthorized use of your Password or any breach of security. You further agree that {context.settings.title} shall not be responsible for your failure to comply with this Section or any loss or damage arising out of, or related to, your use of your Password by you or anyone other than {context.settings.title}. You also agree to take responsibility for all purchases and other activities on or under any account registered to you, and you accept all risks for any unauthorized use of your account.

                    <h3>Charges and Payment</h3>
                    In certain instances, {context.settings.title} may charge a user fee, subscription fee, or other fee. In such instances where a fee may be charged, {context.settings.title} will notify you of the fee prior to your incursion of charges.

                    <h3>Disclaimer</h3>
                    ALL PRODUCTS PURCHASED ON OR THROUGH THIS WEBSITE ARE SUBJECT ONLY TO ANY APPLICABLE WARRANTIES OF THEIR RESPECTIVE MANUFACTURERS, DISTRIBUTORS, AND SUPPLIERS, IF ANY, AND THIS WEBSITE IS PROVIDED BY {context.settings.title} ON AN "AS IS" AND "AS AVAILABLE" BASIS. {context.settings.title} MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, AS TO THE OPERATION OF THIS WEBSITE OR THE INFORMATION INCLUDED ON THIS WEBSITE. {context.settings.title} DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, TITLE, CUSTOM, TRADE, QUIET ENJOYMENT, SYSTEM INTEGRATION, AND FREEDOM FROM COMPUTER VIRUS OR OTHER HARMFUL COMPONENTS. {context.settings.title} DOES NOT REPRESENT OR WARRANT THAT THE FUNCTIONS CONTAINED IN OR ON THIS WEBSITE WILL BE ERROR-FREE OR UNINTERRUPTED, THAT DEFECTS WILL BE CORRECTED, OR THAT THE WEBSITE OR THE SERVER THAT MAKES THE WEBSITE WILL BE AVAILABLE AND FREE FROM ANY HARMFUL COMPONENTS, INCLUDING VIRUSES OR OTHER HARMFUL COMPONENTS. {context.settings.title} DOES NOT MAKE ANY REPRESENTATIONS OR WARRANTIES THAT ALL PRODUCT DESCRIPTIONS, PHOTOGRAPHS, PRICING, PROMOTIONS, OFFERS, AVAILABILITY, OR THAT THE INFORMATION ON THIS WEBSITE IS ACCURATE, COMPLETE, CURRENT, CORRECT, ADEQUATE, USEFUL, TIMELY, RELIABLE, ERROR-FREE, OR OTHERWISE. IF ANY INFORMATION IN OR ON THE WEBSITE IS INACCURATE, INCOMPLETE, OR OUT OF DATE, {context.settings.title} RESERVES THE RIGHT TO CORRECT, CHANGE, OR UPDATE SUCH INFORMATION OR TO CANCEL ORDERS RELATED TO SUCH INFORMATION WITHOUT PRIOR NOTICE (INCLUDING AFTER YOU HAVE SUBMITTED AN ORDER). YOU ACKNOWLEDGE, BY YOUR USE OF THIS WEBSITE, THAT YOU ARE DOING SO AT YOUR OWN RISK.

                    <h3>Limitation of Liability</h3>
                    UNDER NO CIRCUMSTANCES AND UNDER NO LEGAL OR EQUITABLE THEORY, WHETHER IN TORT, CONTRACT, STRICT LIABILITY, OR OTHERWISE, SHALL THE "{context.settings.title} PARTIES" (WHICH IS DEFINED TO INCLUDE ENTITIES THAT ANY OF THE {context.settings.title} ENTITIES MAY ACQUIRE, PURCHASE, OR ABSORB IN THE FUTURE; AND ANY JOINT VENTURES NOW EXISTING OR HEREAFTER CREATED BY THE {context.settings.title} ENTITIES; ALONG WITH THEIR PRESENT, PAST, AND FUTURE DIRECT AND INDIRECT PARENT COMPANIES, SUBSIDIARIES, DIVISIONS, AND RELATED ENTITIES; AS WELL AS EACH OF THE PRESENT, PAST, AND FUTURE OFFICERS, DIRECTORS, MEMBERS, MANAGERS, EMPLOYEES, SHAREHOLDERS, OWNERS, INVESTORS, FUNDS, VENDORS, ATTORNEYS, INSURERS, REPRESENTATIVES, AGENTS, INDEMNITORS, SUCCESSORS, PREDECESSORS (INCLUDING ENTITIES THEY HAVE ACQUIRED, PURCHASED OR ABSORBED), ASSIGNS, HEIRS AND FAMILY MEMBERS OF ANY OF THE FOREGOING; AND EACH OF ALL OF THEIR RESPECTIVE DIRECT AND INDIRECT OWNERS, MANAGEMENT, CONTROLLING PARTIES, ENTITIES UNDER COMMON CONTROL, OFFICERS, MEMBERS, PARTNERS, DIRECTORS, SERVANTS, AGENTS, EMPLOYEES, INCORPORATORS, SHAREHOLDERS, INVESTORS, MANAGERS, PRINCIPALS, INVESTMENT ADVISORS, CONSULTANTS, EMPLOYEES, REPRESENTATIVES, ATTORNEYS, ACCOUNTANTS, LENDERS, UNDERWRITERS, INSURERS, VENDORS, AND SERVICE PROVIDERS) BE LIABLE TO YOU OR TO ANY OTHER PERSON FOR ANY INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL LOSSES OR DAMAGES OF ANY NATURE ARISING OUT OF, OR IN CONNECTION WITH, THE USE OF OR ACCESS TO OR INABILITY TO USE OR ACCESS THIS WEBSITE, INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOST PROFITS, LOSS OF GOODWILL, LOSS OF DATA, WORK STOPPAGE, ACCURACY OF RESULTS, OR COMPUTER FAILURE OR MALFUNCTION, DAMAGE TO YOUR OR A THIRD PERSON'S COMPUTER AND/OR ITS CONTENTS, EVEN IF AN AUTHORIZED REPRESENTATIVE OF {context.settings.title} HAS BEEN ADVISED OF OR SHOULD HAVE KNOWN OF THE POSSIBILITY OF SUCH DAMAGES. YOU AGREE THAT YOU, AND NOT {context.settings.title}, SHALL ASSUME THE ENTIRE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION IN THE EVENT OF ANY SUCH LOSS OR DAMAGE. IN NO EVENT WILL ANY OF THE {context.settings.title} PARTIES BE LIABLE FOR ANY DAMAGES IN EXCESS OF ONE HUNDRED UNITED STATES DOLLARS ($100.00) FOR ANY CLAIMS ARISING FROM OR RELATED TO THESE TERMS & CONDITIONS.

                    <h3>Indemnification</h3>
                    YOU AGREE TO DEFEND, INDEMNIFY, AND HOLD THE {context.settings.title} PARTIES HARMLESS FROM AND AGAINST ANY AND ALL CLAIMS, DAMAGES, COSTS, AND EXPENSES, INCLUDING ATTORNEYS' FEES, ARISING FROM OR RELATED TO (I) YOUR USE OF THIS WEBSITE OR ANY PRODUCTS OBTAINED THROUGH THIS WEBSITE AND/OR (II) YOUR BREACH OF ANY OF THE TERMS OR CONDITIONS CONTAINED HEREIN.

                    <h3>Term and Termination</h3>
                    {context.settings.title} shall have the right to terminate your access to, and use of, the Website and to block or prevent future access to and use of the Website and to delete your account and any related information immediately, if, in its sole discretion, {context.settings.title} believes that your conduct fails to conform with these Terms & Conditions. {context.settings.title} also reserves the right to investigate suspected violations of these Terms & Conditions, including without limitation any violation arising from any submission, posting, or e-mails you make or send to the Website. Upon termination of these Terms & Conditions, all rights granted to you under these Terms & Conditions will cease immediately, and you agree that you will: (a) immediately discontinue use of the Website(s); and (b) as applicable, pay any amounts owed to {context.settings.title} in full within thirty (30) days from the date of such termination.

                    <h3>Applicable Laws</h3>
                    These Terms & Conditions shall be governed by and construed under the laws of the State of Illinois, without regard to conflicts of laws principles.

                    <h3>Arbitration</h3>
                    You agree that any dispute, claim, or controversy arising from or otherwise related to your use of the Website, purchases from the Website, these Terms & Conditions or the breach thereof, including disputes about the validity, scope, or enforceability of this arbitration provision, shall be resolved individually, without resort to any form of class action, and exclusively submitted to binding arbitration administered by the American Arbitration Association ("AAA") in accordance with its Commercial Arbitration Rules. The Arbitration shall take place in Champaign County, Illinois, before a single arbitrator. Judgment on the award rendered by the arbitrator may be entered and enforced in any court having jurisdiction over the subject matter.

                    <h3>Commencement of Actions</h3>
                    ANY CAUSE OF ACTION OR CLAIM THAT YOU MAY HAVE WITH RESPECT TO THIS WEBSITE MUST BE COMMENCED WITHIN ONE-YEAR AFTER SUCH CLAIM OR CAUSE OF ACTION ARISES.

                    <h3>Miscellaneous</h3>
                    The failure of {context.settings.title} to act with respect to a breach of these Terms & Conditions by you or others does not constitute a waiver and shall not limit {context.settings.title} rights with respect to such breach or any subsequent breaches. Neither the course of conduct between the parties nor trade practice shall act to modify these Terms & Conditions. {context.settings.title} may assign its rights and duties hereunder to any party at any time without any notice to you. These Terms & Conditions may not be assigned by you without {context.settings.title} prior written consent. If any provision of these Terms & Conditions shall be unlawful, invalid, void, or for any reason unenforceable, then that provision shall be deemed severable from these Terms & Conditions and shall not affect the validity and enforceability of any remaining provisions. These Terms & Conditions may not be modified except in writing, signed by both parties.
                    <br /><br />
                    <h3>Forward-Looking Statements</h3>
                    These Terms & Conditions and the documents incorporated by reference herein, if any, may contain forward-looking statements within the meaning of Section 27A of the Securities Act of 1933 and Section 21E of the Securities Exchange Act of 1934. Such statements are based on management's current expectations and assessments of risks and uncertainties and reflect various assumptions concerning anticipated results, which may or may not prove to be correct. Some of the factors that could cause actual results to differ materially from estimates or projections contained in such forward-looking statements include the pattern of brand sales, including variations in sales volume within periods; competition within the relevant product markets, including the ability to develop and successfully introduce new products, ensuring product quality, pricing, promotional activities, introduction of competing products, and continuing customer acceptance of existing products; loss of distributorship rights; risks inherent in acquisitions and strategic alliances; the loss of one or more key employees; the effects of a prolonged United States or global economic downturn or recession; changes in costs, including changes in labor costs, raw material prices, or advertising and marketing expenses; the costs and effects of unanticipated legal or administrative proceedings; and variations in political, economic, or other factors such as currency exchange rates, inflation rates, tax changes, legal and regulatory changes, or other external factors over which {context.settings.title} has no control. {context.settings.title} has no obligation to update any forward-looking statement in these Terms & Conditions or any other document incorporated herein.

                    <h2>{context.settings.title} TERMS &amp; CONDITIONS</h2>
                    <h3>General</h3>
                    By shopping at the {context.settings.title}, you acknowledge and agree to be bound by these {context.settings.title} Terms & Conditions, in addition to the General Terms & Conditions. These {context.settings.title} Terms & Conditions apply to all offers, agreements, and transactions that are made or entered into in connection with the sale and delivery of products from the {context.settings.title}.
                    <br /><br />
                    These {context.settings.title} Terms &amp; Conditions are to supplement the General Terms &amp; Conditions listed above, in addition to supplementing the {context.settings.title} Privacy Policy, and all other policies posted on {window.location.href} or any of its sub-pages, all of which are incorporated herein by reference. Since these incorporated policies will also be applicable to your visit to the {context.settings.title}, please review all policies prior to placing an order.
                    <br /><br />
                    To the extent these {context.settings.title} Terms & Conditions are inconsistent or incompatible with the General Terms & Conditions listed above, these {context.settings.title} Terms & Conditions will supersede and prevail with respect to your use of the {context.settings.title}.

                    <h3>Account Registration</h3>
                    A registered account is not required in order to shop at the {context.settings.title}. To make online shopping faster and easier, however, you may choose to register for an account with {context.settings.title} Franchisor SPV, LLC. Please confirm your email address when creating your account, as we will use the email address on file to contact you with any issues concerning your order. If you do not wish to set up a registered account, you may still shop and purchase as a "Guest." Whether you create a registered account or complete your purchase as a Guest, you agree to provide honest, accurate, current, and complete information, and to keep your information updated and accurate.

                    <h3>Online Availability</h3>
                    {context.settings.title} strives to have the latest and greatest styles available for purchase in every size. If the style or size you want is not listed, it is not available. Although the {context.settings.title} is designed to feature "real-time" inventory levels so that only in-stock items are visible and available for purchase, we may experience shortages of stock in a particular style or size, and cannot guarantee that items which appear to be in stock are actually available. All items are subject to availability and we reserve the right to impose quantity limits on any order, to reject all or part of an order, and to discontinue products without notice, even if you have already placed your order. If the item you would like to purchase is currently out of stock, we apologize for the inconvenience and encourage you to call our customer service line at 866.276.6302, so that we may help you find a similar product.

                    <h3>Ordering and Changes to Orders</h3>
                    When you place an order we will send a confirmation email to the address that you have provided. If you are using your workplace email address, please be aware that many companies use spam filters to disqualify incoming automated emails, which could impede the delivery of our confirmation email to you or send it to junk mail.
                    <br /><br />
                    The "Confirmation" page sets out the final details of your order. After you have reviewed the Confirmation page and opted to proceed with your order, we will send you an order acknowledgement email detailing the products that you have ordered. Please note that this email does not serve as either an order confirmation or order acceptance from {context.settings.title}.
                    <br /><br />
                    Acceptance of your order and the completion of the agreement between you and {context.settings.title} Franchisor SPV, LLC for your order will occur upon our dispatch to you of the products ordered, unless we have notified you that we do not accept your order or you have cancelled it. {context.settings.title} reserves the right to accept or decline your order for any reason up until the time the product is actually delivered to you. {context.settings.title} reserves the right to limit or prohibit orders that {context.settings.title} believes, in its sole discretion, may be placed by dealers, resellers or distributors.
                    <br /><br />
                    Due to the short timeframe between order and shipment, it is difficult to make changes once your order has been placed. If you contact our customer service team before shipping arrangements have been initiated, however, we will do our best to facilitate a change.

                    <h3>Tax</h3>
                    Where applicable, sales tax will be assessed on each order at the applicable local rate. You agree that taxes may be adjusted from the amount shown on the payment screens. You are solely responsible for any and all duties, taxes, levies, or fees (including any sales, use, or withholding taxes) imposed on or in connection with purchases from the Website by any authority.

                    <h3>Payment</h3>
                    Personal checks, money orders, and cash payments are not acceptable forms of payment at the {context.settings.title}. We may require credit cards and debit cards to be issued by an institution in the jurisdiction in which you are located, and those forms of payment must be linked to a billing address in the same jurisdiction. For most jurisdictions, you must ensure that the billing address associated with the credit- or debit-card issuing bank is the same billing address that you enter when ordering. {context.settings.title} reserves the right to supplement the list of acceptable forms of payment at the {context.settings.title}.
                    <br /><br />
                    Because {context.settings.title} Franchisor SPV, LLC does not charge for items until they ship, we may use a pre-authorization process to reserve your products for shipment. In order to avoid unnecessary overdraft charges, a method called a "pre-authorization" is often used by banks to verify that the credit/debit card in use is valid and has sufficient funds. Most authorizations expire within five to seven days, but the issuing bank ultimately determines the length of the authorization. The final credit- or debit-card charge will only reflect the value of your shipped merchandise plus applicable shipping and taxes.
                    <br /><br />
                    If you are experiencing problems with payment, please contact our customer service line at 866.276.6302, and a member of our team will be happy to assist you.

                    <h3>Cancellations, Exchanges, and Refunds</h3>
                    ALL SALES ARE FINAL. EXCHANGES AND REFUNDS WILL NOT BE PERMITTED. Prior to fulfillment of an order, however, you may cancel your order by contacting our customer service team at 866.276.6302. Once an order has been fulfilled, the order will be deemed to be completed, and {context.settings.title} will no longer be able to cancel the order or offer a refund.

                    <h3>Product Descriptions and Pricing</h3>
                    {context.settings.title} aims to be as accurate as possible. {context.settings.title} makes no warranty, however, that product descriptions, colors, photographs, videos or other product related content on the {context.settings.title} are wholly accurate, complete, reliable, current, or error-free. {context.settings.title} cannot guarantee that your computer or device's display of color or other product features is accurate.
                    <br /><br />
                    Despite our best efforts, a small number of items may be mispriced. If the correct price of an item sold by {context.settings.title} is higher than our stated price, we will, at our discretion, either contact you for instructions before shipping or cancel your order and notify you of such cancellation. The prices displayed on the {context.settings.title} are quoted in United States Dollars.

                    <h3>Changes</h3>
                    Please note that, subject to applicable law, we reserve the right to change the goods advertised or offered for sale through the {context.settings.title}, the prices or specifications of any such goods and any promotional offers and any content available at the {context.settings.title} at any time and from time to time without any notice or liability to you or any other person.

                    <h2>
                        {context.settings.title} POLICY REGARDING SUBMISSIONS,
                        POSTINGS AND OTHER COMMUNICATIONS
                    </h2>
                    All submissions, postings, and email communications to or through the Website shall be subject to this {context.settings.title} Policy Regarding Submissions, Postings, and Other Communications.

                    <h3>Submissions</h3>
                    All remarks, suggestions, ideas, graphics, or other information communicated by you to {context.settings.title} through the Website (collectively, "Submissions") will forever be the property of {context.settings.title} and you waive all of your rights, including but not limited to moral rights, therein if applicable, provided that you will continue to be responsible for the content of Submissions including, without limitation, any indemnification obligations related to such Submissions. {context.settings.title} will not be required to treat any Submissions as confidential (unless required by law or if {context.settings.title} has agreed to treat it as confidential in other documentation), and will not be liable for any ideas for its business (including without limitation, product or advertising ideas) and will not incur any liability as a result of any similarities that may appear in future {context.settings.title} operations. Without limitation, {context.settings.title} will have exclusive ownership of all present and future existing rights to Submissions of every kind and nature, and will be entitled to use Submissions for any commercial or other purpose whatsoever without compensation to you or any other person sending Submissions. {context.settings.title} retains the right to review, edit or delete from the Website all Submissions that {context.settings.title}, in its sole discretion, considers illegal, offensive, in violation of third party rights, or is otherwise inappropriate.

                    <h3>Email and Other Communications</h3>
                    In connection with your use of the Website, you consent to {context.settings.title} recording any communication, electronic or otherwise, between you and {context.settings.title} and retaining any information and data that you submit while using the Website or making a purchase from the Website. In using the Website, you may be permitted to communicate electronically with {context.settings.title} by sending electronic mail to {context.settings.title}; however, you acknowledge and agree that only general information or inquiries may be submitted to {context.settings.title} via electronic mail and any other submissions or communications on or through the Website (e.g., the placement of orders) may be submitted only in accordance with the express instructions set forth on the Website for such submissions or communications. Please do not send any time-sensitive communications to {context.settings.title} via e-mail, as {context.settings.title} is not responsible for responding to any such communications.

                    <h3>Investigations</h3>
                    {context.settings.title} may seek to gather information from the user who is suspected of violating these Terms & Conditions, and from any other user. {context.settings.title} may suspend any users whose conduct or postings are under investigation and may remove such material from its servers as it deems appropriate and without notice. If {context.settings.title} believes, in its sole discretion, that a violation of these Terms & Conditions has occurred, it may edit or modify any submission, posting or e-mail, remove the material permanently, cancel postings, warn users, suspend users and passwords, terminate accounts or take any other corrective action as it deems appropriate. {context.settings.title} will fully cooperate with any law enforcement authorities or court order requesting or directing {context.settings.title} to disclose the identity of anyone posting any e-mails, or publishing or otherwise making available any materials that are believed to violate these Terms & Conditions. YOU WAIVE AND HOLD HARMLESS {context.settings.title} FROM ANY CLAIMS RESULTING FROM ANY ACTION TAKEN BY {context.settings.title} DURING OR AS A RESULT OF ITS INVESTIGATIONS AND/OR FROM ANY ACTIONS TAKEN AS A CONSEQUENCE OF INVESTIGATIONS BY EITHER {context.settings.title} OR LAW ENFORCEMENT AUTHORITIES.

                    <h2>ONLINE COPYRIGHT INFRINGEMENT NOTIFICATION POLICY</h2>
                    If you believe that this Website(s) contains materials that constitute copyright infringement, please notify {context.settings.title} in accordance with this Online Copyright Infringement Notification Policy.
                    If you believe that the Website contains materials that constitute copyright infringement, please notify us via our contact form.
                </div>
            </div>
        </div>);
}
export default Terms;